In [2]:
import numpy as np

In [11]:
m = 3

In [12]:
X = np.array([[1,10], [1,5], [1,4]])
X

array([[ 1, 10],
       [ 1,  5],
       [ 1,  4]])

In [60]:
y = np.array([[7], [4], [3]])
y

array([[7],
       [4],
       [3]])

In [61]:
theta = np.array([[0.5], [0.1]])
theta

array([[0.5],
       [0.1]])

In [62]:
X@theta

array([[1.5],
       [1. ],
       [0.9]])

In [63]:
X@theta - y

array([[-5.5],
       [-3. ],
       [-2.1]])

In [64]:
(X@theta-y).sum()

-10.6

In [65]:
dth0 = (1/m)*((X@theta-y).sum())
dth0

-3.533333333333333

In [66]:
J = (1/(2*m))*(((X@theta-y)**2).sum())
J

7.2766666666666655

In [73]:
X@theta-y

array([[-5.5],
       [-3. ],
       [-2.1]])

In [74]:
X[:,1]

array([10,  5,  4])

In [77]:
X[:,1]@(X@theta-y)

array([-78.4])

In [80]:
dth1 = (1/m)*(X[:,1]@(X@theta-y))
dth1

-26.133333333333333

In [81]:
[[dth0], [dth1[0]]]

[[-3.533333333333333], [-26.133333333333333]]

In [85]:
dth0 = (1/m)*(X[:,0]@(X@theta-y))
dth0

array([-3.53333333])

In [86]:
dth1 = (1/m)*(X[:,1]@(X@theta-y))
dth1

array([-26.13333333])

In [90]:
dth = (1/m)*(X.T @ (X@theta-y))
dth

array([[ -3.53333333],
       [-26.13333333]])